### ISSUE TITLE
[Request] Unraid Support

### ISSUE THREAD

**Issue by al3x1337** [HeyPuter/puter#185]
A Community App compatible version of Putty would be great for Unraid users. Currently can't figure out how to install this manually with Docker Compose Manger and can't find it on Dockerhub either.

**Comment by AtkinsSJ** [comment]
Hi there! 

I'm not familiar with Unraid so just trying to make sure I understand what you're asking for: You want to control a remote server running Unraid, by using a Putty app (or similar) inside Puter?

**Comment by Wdrussell1** [comment]
Unraid is a type of hypervisor that runs on baremetal. What they are requesting is that you build a docker container that can be imported into Unraid easily using their Community Apps plugin. 

https://unraid.net/community/apps

https://forums.unraid.net/topic/87144-ca-application-policies-notes/

**Comment by KernelDeimos** [comment]
Is this url what you're looking for? ghcr.io/heyputer/puter:latest

**Comment by al3x1337** [comment]
> Hi there!
> 
> I'm not familiar with Unraid so just trying to make sure I understand what you're asking for: You want to control a remote server running Unraid, by using a Putty app (or similar) inside Puter?

Self hosting Puter on Unraid. Having a Community App template would open up ease of installation for users on Unraid.

Using Docker Compose Manager (app), I was able to paste the following docker-compose template with the volumes modified to match. I ran New Permissions from the Tools menu on Unraid on the share that has my volume I modified from the Docker-Compose and was able to get to the Login Screen after bringing it up.

```
version: "3.8"
services:
  puter:
    container_name: puter
    image: ghcr.io/heyputer/puter:latest
    pull_policy: always
    # build: ./
    restart: unless-stopped
    ports:
      - '4100:4100'
    environment:
      # TZ: Europe/Paris
      # CONFIG_PATH: /etc/puter
      PUID: 1000
      PGID: 1000
    volumes:
      - ./puter/config:/etc/puter
      - ./puter/data:/var/puter
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://puter.localhost:4100/test || exit 1
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s
```

![image](https://github.com/HeyPuter/puter/assets/44815197/2c7149c5-908e-4cfc-963b-6da08ef79f3d)

I viewed the logs and have gotten the password for the default_user account but receive a red empty error box above the username field when attempting to login. The logs don't show any errors or provide helpful insight.

This is as far as I was able to get so far, hopefully someone can respond below if they manage to get it running and logged in successfully.
