### ISSUE TITLE
Missing linux/arm64 docker build 

### ISSUE THREAD

**Issue by PalRist** [HeyPuter/puter#214]
**Issue Description**
Docker log: 
exec /usr/local/bin/docker-entrypoint.sh: no such file or directory

**Steps to Reproduce**
Portainer running this stack:

---
version: "3.8"
services:
  puter:
    image: ghcr.io/heyputer/puter:latest
    container_name: puter
    build: ./
    ports:
      - 4100:4100
    restart: unless-stopped

**Tooling**
- Portainer running on raspbian, RPi5

**Comment by zarevskaya** [comment]
Try:

```
version: "3.8"
services:
  puter:
    container_name: puter
    image: ghcr.io/heyputer/puter:latest
    pull_policy: always
    # build: ./
    restart: unless-stopped
    ports:
      - '4100:4100'
    environment:
      # TZ: Europe/Paris
      # CONFIG_PATH: /etc/puter
      PUID: 1000
      PGID: 1000
    volumes:
      - ./puter/config:/etc/puter
      - ./puter/data:/var/puter
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://puter.localhost:4100/test || exit 1
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s
```

**Comment by PalRist** [comment]
Thanks for the proposal! However, i still get the same message (after purging any remains from my last attempt):
exec /usr/local/bin/docker-entrypoint.sh: no such file or directory

**Comment by KernelDeimos** [comment]
I have never used portainer before - does it have specific requirements of the image contents to successfully load? (i.e. do we need to provide a `docker-entrypoint.sh` file to be compatible with portainer?) - I ask because this filename is not familiar to me. The entrypoint for our docker container is `npm start`.

Also, very cool that you're trying this on a Raspberry Pi! I'm curious to find out how this goes.

**Comment by MohamedElashri** [comment]
> @KernelDeimos i am not sure how to check, but perhaps you know; Is the image built for ARM64 devices?

No, The official image does not get built for arm64. I would suggest adding 
```
platforms: linux/amd64,linux/arm64
```

to the build [logic](https://docs.docker.com/build/ci/github-actions/multi-platform/) in GitHub action 

```
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
		  platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```

or you can build it youself (you can do this in portainer by cloning puter repo so that Dockerfile and src files are in the context) and use this `docker-compose.yml` version 


```yml
version: "3.8"
services:
  puter:
    container_name: puter
    pull_policy: always
    build: ./
    restart: unless-stopped
    ports:
      - '4100:4100'
    environment:
      # TZ: Europe/Paris
      # CONFIG_PATH: /etc/puter
      PUID: 1000
      PGID: 1000
    volumes:
      - ./puter/config:/etc/puter
      - ./puter/data:/var/puter
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://puter.localhost:4100/test || exit 1
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s
```

**Comment by KernelDeimos** [comment]
I just updated the file with [several platforms added](https://github.com/HeyPuter/puter/commit/e8935f5582e7bf1b70244a86e2494ee22ebf779b) - I don't know which ones will work, but I also don't know what the rationale is of the software blocking people from attempting to run this on specific platforms based on a non-optional includes list. This seems like a violation of separation of concerns to me; we depend on node, so Puter will run on whatever platforms node runs on; it's weird that I have to care what platforms node runs on (in this specific context).

**Comment by MohamedElashri** [comment]
> I just updated the file with [several platforms added](https://github.com/HeyPuter/puter/commit/e8935f5582e7bf1b70244a86e2494ee22ebf779b) - I don't know which ones will work, but I also don't know what the rationale is of the software blocking people from attempting to run this on specific platforms based on a non-optional includes list. This seems like a violation of separation of concerns to me; we depend on node, so Puter will run on whatever platforms node runs on; it's weird that I have to care what platforms node runs on (in this specific context).

There is a problem with this action. It seems that `docker/build-push-action@v5` don't add buildx by default. This is why we get this error 

```
ERROR: Multi-platform build is not supported for the docker driver.
Switch to a different driver, or turn on the containerd image store, and try again.
Learn more at https://docs.docker.com/go/build-multi-platform/
Error: buildx failed with: Learn more at https://docs.docker.com/go/build-multi-platform/
```

So we will need to add that before using this action. Sorry my suggestion was incomplete. This should be the [reference](https://docs.docker.com/build/ci/github-actions/multi-platform)

```
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
```

This should be before that. One example could be 


```
name: Docker Image CI

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Package Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU 
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
            type=sha
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6,linux/ppc64le,linux/s390x
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```


Regarding all these platforms. I'm not sure if all of them will work but definitely if you want to build for all of these you will need `QEMU` to emulate the instructions needed for the build 

```
      - name: Set up QEMU 
        uses: docker/setup-qemu-action@v3
```

Which I added in the example above. Would you give it a try ?
