### ISSUE TITLE
Puter docker container cannot start, write to /var/puter

### ISSUE THREAD

**Issue by mfrancisbeehive** [HeyPuter/puter#694]
**Issue Description**

Docker compose not working on Mac. Says it cannot write to /var/puter

**Steps to Reproduce**

1. Create a new directory to hold puter files
2. Change to the directory
3. Paste and run the commands from the README for Docker Compose on Mac/Linux

**Expected & Actual Behavior**

Puter should start and run as normal

**Addition Information or Screenshots (if applicable)**

<img width="783" alt="Captura de pantalla 2024-08-14 a la(s) 4 30 38 p m" src="https://github.com/user-attachments/assets/0c25e731-a7f8-4369-9f16-2a4b1d73d031">

**Deployment**
- [ ] Production (puter.com)
- [ ] Development (`npm run start`)
- [ ] Docker (via `docker run`)
- [x] Docker (via `docker-compose`)

**Puter version (if accessible)**
> Click the profile button on the top-right, then "Settings". The version number will be printed at the bottom
latest as of this issue submission

**Comment by KernelDeimos** [comment]
Hello, I'm not able to reproduce this issue. Please ensure you're running `docker compose up` in the correct directory - a directory containing a subdirectory `puter` with the sub-directories `data` and `config`.

Also you may want to know that running with `docker compose` currently comes with a disadvantage. The  development console gets completely obliterated by Docker and you will be unable to get the password for the `admin` user or run any dev console commands.

**Comment by Roi-Danton** [comment]
I have the same problem.
Did a fresh installation.

There are two options described how to do puter with docker. 
None of them work for me.

**Comment by DevBengel** [comment]
Same here- i mounted two new docker volumes to puter. Same result. Its a permission issue. If you really chown the directories and/or volumes like stated (chown -R 1000:1000 puter) you are allowed to write.
This is just a workaround in my opinion...

Best regards

**Comment by Roi-Danton** [comment]
Nope, this doesn't work for me. 
I tried every right I know. 
The UID 1000 is set in the yml file right?
Because 1000 is another user for me. Not the one running the container.

**Comment by dennysubke** [comment]
> Same here- i mounted two new docker volumes to puter. Same result. Its a permission issue. If you really chown the directories and/or volumes like stated (chown -R 1000:1000 puter) you are allowed to write. This is just a workaround in my opinion...
> 
> Best regards

Didn't work for me... It's frustrating.

**Comment by dennysubke** [comment]
I want to install Puter on my [umbrel home server](https://umbrel.com/umbrel-home) using docker-compose. All configurations were carried out as described in the docs. Umbrel can be reached via the address **umbrel.local**. Unfortunately after the installation I get the following screen:


![1-puterscreen](https://github.com/user-attachments/assets/40c8df45-6b21-433c-9f4f-4f7555c0955d)
##
I mounted the config in the following directory: `${APP_DATA_DIR}/config:/volatile/config` 
A **config.json** was not generated. So I added it with the following content:

```
{
  "server_id": "umbrel.local",
  "http_port": "4100",
  "domain": "umbrel.local",
  "pub_port": "4100"
}
```
##

Nevertheless, I get the error message from the screen above, even though according to the logs everything should be fine. The username and password are also generated.


![2-puterlogs](https://github.com/user-attachments/assets/f3fba5a9-f9be-4292-a942-a0964d22a06b)

##
Here the [docker-compose.yml](https://github.com/dennysubke/dennys-umbrel-app-store/blob/master/denny-puter/docker-compose.yml) can be found from my [repository](https://github.com/dennysubke/dennys-umbrel-app-store/tree/master/denny-puter).


I've already tried a lot, but I've now reached the end. There has to be a solution?!?! I would be grateful for any help or ideas. 😎


@KernelDeimos , maybe you?

**Comment by KernelDeimos** [comment]
I see some of you were observing the output in a terminal, which tells me you were running the Docker container on a local machine. I would recommend for local running to just use node. The docker container rarely works properly for anyone, and we don't use it ourselves. It has been more painful to attempt to support Docker than it has been to support Windows, and I say that while knowing the server likely doesn't currently run under Windows.

As for @dennysubke I think you brought this up in a separate issue and we're handling it there - can you confirm? (we had a bit of backlog, so I'm going through all the issues again)

**Comment by arkilis** [comment]
Not working on M4 as well.

**Comment by dennysubke** [comment]
@arkilis Thanks for your hint. Doesn't work for me. This has already been discussed elsewhere. It is definitely a problem in the docker container.

**Comment by VirajSingh19** [comment]
can we update the docs to `sudo chmod -R 777 puter` ?

**Comment by KernelDeimos** [comment]
> [@arkilis](https://github.com/arkilis) Thanks for your hint. Doesn't work for me. This has already been discussed elsewhere. It is definitely a problem in the docker container.

That was a non-sequitur. If you believe there's an issue in the docker container then you must have more information you can provide to us to help us resolve the issue, right?

**Comment by KernelDeimos** [comment]
> can we update the docs to `sudo chmod -R 777 puter` ?

We _could_, and it would work for more people, but that's not actually the right solution. The docker container is supposed to be deterministic, so it's strange that the uid of `1000` isn't consistent for everyone. Someone needs to provide more information if we're to resolve this issue; as it is now, there's nothing useful we can do because we simply don't have the information. Docker container works fine for me, so I can't reproduce the issue to further diagnose it myself.

**Comment by LittleNewton** [comment]
I cannot accept `sudo chmod -R 777 puter`. It is totally not secure!

**Comment by LittleNewton** [comment]
And I don't think making /var/puter writable is a good idea.

```yml
# Author: Peng Liu
# Email: littlenewton6@gmail.com
# Created: 17 Oct. 2025
# Updated: 17 Oct. 2025
# Official Release: https://github.com/HeyPuter/puter

services:
  puter:
    container_name: puter
    image: ghcr.io/heyputer/puter:latest
    pull_policy: always
    # build: ./
    restart: unless-stopped
    ports:
      - '4100:4100'
    environment:
      TZ: Asia/Shanghai
      CONFIG_PATH: /etc/puter
      PUID: 1000
      PGID: 1000
    volumes:
      - ${APPDATA_PATH}/Puter:/etc/puter
      - ${NAS_DOC_PATH}:/var/puter/Documents:ro
      - ${NAS_SOFTWARE_PATH}:/var/puter/Software:ro
      - ${NAS_DROPBOX_PATH}:/var/puter/Dropbox:ro
      - ${NAS_DOWNLOADS_PATH}:/var/puter/Downloads:ro
      - ${NAS_MEDIA_PATH}:/var/puter/Media:ro
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://puter.localhost:4100/test || exit 1
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s
```

I just want a simple file browser, so read-only is the best choice.
