### ISSUE TITLE
invalid host header

### ISSUE THREAD

**Issue by rajivraghu** [HeyPuter/puter#785]
Hello Dev,
I opened the project in github codespace.. 
did npm install
npm start

then i port forwaded  
![image](https://github.com/user-attachments/assets/6de750ca-02bd-4798-878b-89d3c45d7260)

When i open the url that github codespace provides ...
Ex:https://improved-disco-jgrv49xw4p3qjgj-4100.app.github.dev/
**It says invalid host header**

![image](https://github.com/user-attachments/assets/d60951e3-4785-4a3a-80c0-e52e3c148821)

**Comment by ajaymajgaonkar** [comment]
Same error for docker compose on linux

**Comment by jelveh** [comment]
I suspect this is because you might be using a custom domain. Could you follow the [instructions here](https://github.com/HeyPuter/puter/blob/main/doc/self-hosters/instructions.md#domain-name) and let me know if the issue persists?

**Comment by dovholuknf** [comment]
I'm running in docker compose, i have an /etc/puter/config.json. I ensured the domain is set:
```
docker exec -it browzerdc-puter-1 grep domain /etc/puter/config.json
    "domain": "puter.clint.demo.openziti.org",
```
I bounced the container via compose down / compose up yet still the header seems not to be respected. Is it possible to mount in the config to be sure it's the proper one being read/used?

I tried running interactively to see if there was any log on startup indicating the domain being used but there's no log. I also found and edited the 'protocol' but still no luck.
```
    "protocol": "https",
```

It's an interesting demo, I like using it if I can get by this

**Comment by ahakobyan79** [comment]
I was trying to install Puter locally, kept getting this same error:
Hardware:
CPU: Intel i7
RAM: 16gb
SSD: 128gb

NodeJs tried: 18, 21, 22, 23 (none worked)
npm: 10.9

OS: Ubuntu Server 23, Zorin OS 17.2

I tried all options above, tried reinstalling multiple times, tried openning both with IP:4100 and with http://puter.localhost:4100

I get nothing at all with puter.localhost, and IP:4100 returns "Invalid Host header."

What am I missing here?

**Comment by Byarain** [comment]
I have also encountered the same issue and have tried it in different environments.

**Comment by KernelDeimos** [comment]
We're missing a piece of information to resolve this issue; I don't know how to reproduce this without configuring the domain incorrectly. If anybody can provide clear reproduction steps, that will help us resolve this issue. I expect this happens on environments that are difficult to support or is a common configuration mistake that we need to document more clearly.

Here's why this issue specifically impacts Puter, while you might not run into this issue with other projects:
- We need multiple domains because Puter apps run in iframes that communicate with our API. There is no secure way to accomplish this without multiple origins.
- The above completely rules out connecting directly with the IP address.
- The above two points mean any reverse proxy configuration is going to require careful configuration to avoid complications.

(tangent: If browsers supported multiple "virtual" origins on a single origin, all of this would be a lot easier, and projects like Puter could be hosted securely without needing domain configuration at all. It seems crazy to me that this isn't a thing yet.)

**Comment by g0ldingkev** [comment]
i've tried this on ubuntu 22.04 with NO domain, just plain vanilla deployment

administrator@UBNT001:~$ hostname -f
UBNT001

**Comment by flintstones-fred** [comment]
@KernelDeimos I am not the OP. But I would like to provide detailed instructions on how to reproduce the issue. 
I am not using an external domain. Everything is internal to my network. Here is the docker-compose file I am using - 

### Step 1: Create `puter/data` and `puter/config` directories:
```
mkdir -p /opt/puter/data /opt/puter/config
mkdir -p /opt/puter/config
chown -R 1000:1000 /opt/puter
```

### Step 2: Prepare the docker-compose. I am using Dockage to maintain my containers, but I don't think that should matter. Here is the docker-compose I am using:
```
services:
  puter:
    container_name: puter
    image: ghcr.io/heyputer/puter:latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - 4100:4100
    environment:
      TZ: America/Chicago
      # CONFIG_PATH: /etc/puter
      PUID: 1000
      PGID: 1000
    volumes:
      - /opt/puter/config:/etc/puter
      - /opt/puter/data:/var/puter
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://puter.localhost:4100/test ||
        exit 1
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s
networks: {}
```

### Step 3: At this stage, just hit `deploy` in Dockage, which is equivalent to `docker compose up -d`

### Step 4: Navigate to 192.168.1.228:4100 (Note that 192.168.1.228 is my local IP). At this point, I am presented with `Invalid Host header.` as the only text on the webpage.
