### ISSUE TITLE
Error reaching selfhosted instance  - Bad Docker image or a configuration issue? 

### ISSUE THREAD

**Issue by dennysubke** [HeyPuter/puter#799]
As some people have already pointed out, there is something wrong with the Docker image. Attached is my docker-compose.yml:

```
version: "3.9"

services:
  app_proxy:
    environment:
      APP_HOST: denny-puter_web_1
      APP_PORT: 4100
      PROXY_AUTH_ADD: "false"

  web:
    image: ghcr.io/heyputer/puter:release@sha256:ec0fb133779bcdb37987c7776cb7b698876ded3020970d981719b666aed6c094
    restart: on-failure
    environment:
      TZ: Europe/Berlin
      PUID: 1000
      PGID: 1000
    volumes:
      - ${APP_DATA_DIR}/data:/data/.puter
      - ${APP_DATA_DIR}/config:/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://umbrel.local:4100/test || exit 1
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s
```
The config.json file looks like this:
```
{
  "domain": "umbrel.local",
  "http_port": 4100,
  "pub_port": 4100
}
```

After installing everything is fine according to my logs. Here's an excerpt:

```
denny-puter_web_1        | ┃  Puter is now live at: ttp://puter.localhost:4100\http://puter.localhost:4100;;\  ┃
denny-puter_web_1        | ┃  Type web:dismiss to dismiss this message           ┃
denny-puter_web_1        | ┃                                                     ┃
denny-puter_web_1        | ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
denny-puter_web_1        | ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
denny-puter_web_1        | ┃  Your default user has been created!           ┃
denny-puter_web_1        | ┃  username: default_user                        ┃
denny-puter_web_1        | ┃  password: 46dae968                            ┃
denny-puter_web_1        | ┃  (change the password to remove this message)  ┃
denny-puter_web_1        | ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
denny-puter_web_1        | puter> 
[TICK::refresh_apps_cache] (4366.396s) refresh associations cache
denny-puter_web_1        | [ Dev Console ]
denny-puter_web_1        | ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
denny-puter_web_1        | ┃  Node.js version 21 is past EOL by at least 4 months;   ┃
denny-puter_web_1        | ┃  Everything should work, but you should still upgrade.  ┃
denny-puter_web_1        | ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
denny-puter_web_1        | ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
denny-puter_web_1        | ┃                                                     ┃
denny-puter_web_1        | ┃  Puter is now live at: ttp://puter.localhost:4100\http://puter.localhost:4100;;\  ┃
denny-puter_web_1        | ┃  Type web:dismiss to dismiss this message           ┃
denny-puter_web_1        | ┃                                                     ┃
denny-puter_web_1        | ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
denny-puter_web_1        | ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
denny-puter_web_1        | ┃  Your default user has been created!           ┃
denny-puter_web_1        | ┃  username: default_user                        ┃
denny-puter_web_1        | ┃  password: 46dae968                            ┃
denny-puter_web_1        | ┃  (change the password to remove this message)  ┃
```

The app URL should be **http://umbrel.local:4100**

After running I get the login screen with the following error message:

![Screenshot 2024-10-11 182938](https://github.com/user-attachments/assets/702d712f-ba09-4354-93e1-fff15495d570)

The image used here is this: **sha-ec31007**

Since the image was already more than 6 months old, I also tried a newer one (2.4.1). Then I got the following error message:

![Screenshot 2024-10-11 192008](https://github.com/user-attachments/assets/352ec649-bdd2-4d2f-9f9b-a48a09ea03a4)

The logs attached:

[umbrel_denny-puter_2024-10-11_19-21.log](https://github.com/user-attachments/files/17345763/umbrel_denny-puter_2024-10-11_19-21.log)

I've really tried everything and I'm at the end of my knowledge. Can someone from the developers take a look at this? 

Apparently there is actually something wrong with the Docker image.

@KernelDeimos  @jelveh  

Thank you!
