### ISSUE TITLE
Bug:  app-center not found

### ISSUE THREAD

**Issue by snowdream** [HeyPuter/puter#893]
### Issue Description

I try to install it with docker compose.

but i can not find app center on puter

<img width="552" alt="image" src="https://github.com/user-attachments/assets/b711cdd2-3d6d-4e6e-ab8b-904188fd307e">

### Steps to reproduce

```
mkdir -p puter/config puter/data
sudo chown -R 1000:1000 puter
wget https://raw.githubusercontent.com/HeyPuter/puter/main/docker-compose.yml
docker compose up
```

```
---
version: "3.8"
services:
  puter:
    container_name: puter
    image: ghcr.io/heyputer/puter:latest
    pull_policy: always
    # build: ./
    restart: unless-stopped
    ports:
      - '4100:4100'
    environment:
      # TZ: Europe/Paris
      # CONFIG_PATH: /etc/puter
      PUID: 1000
      PGID: 1000
    volumes:
      - ./puter/config:/etc/puter
      - ./puter/data:/var/puter
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://puter.localhost:4100/test || exit 1
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s
```

### Expected behaviour

<img width="651" alt="image" src="https://github.com/user-attachments/assets/9c49e9a4-e60c-4da1-9950-b3cbaebcacfd">

### Deployment

- [ ] Production (puter.com)
- [ ] Development (`npm run start`)
- [ ] Docker (via `docker run`)
- [X] Docker (via `docker-compose`)

### Puter version

latest
